/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package lua.natives;

import lua.*;

final public class JNI_LuaState {

    public static native long internal_native_create_addr();

    public static native void internal_native_deleteNative(long this_addr);

    public static native void internal_native_x_lua_absindex(long this_addr, int idx);

    public static native void internal_native_x_lua_arith(long this_addr, int op);

    public static native int internal_native_x_lua_checkstack(long this_addr, int n);

    public static native int internal_native_x_lua_compare(long this_addr, int index1, int index2, int op);

    public static native void internal_native_x_lua_concat(long this_addr, int op, int n);

    public static native void internal_native_x_lua_copy(long this_addr, int fromidx, int toidx);

    public static native void internal_native_x_lua_createtable(long this_addr, int narr, int nrec);

    public static native int internal_native_x_lua_getfield(long this_addr, int index, String k);

    public static native int internal_native_x_lua_getglobal(long this_addr, String name);

    public static native int internal_native_x_lua_geti(long this_addr, int index, int i);

    public static native int internal_native_x_lua_getmetatable(long this_addr, int index);

    public static native int internal_native_x_lua_gettable(long this_addr, int index);

    public static native int internal_native_x_lua_gettop(long this_addr);

    public static native int internal_native_x_lua_getiuservalue(long this_addr, int index, int n);

    public static native void internal_native_x_lua_insert(long this_addr, int index);

    public static native int internal_native_x_lua_isboolean(long this_addr, int index);

    public static native int internal_native_x_lua_iscfunction(long this_addr, int index);

    public static native int internal_native_x_lua_isfunction(long this_addr, int index);

    public static native int internal_native_x_lua_isinteger(long this_addr, int index);

    public static native int internal_native_x_lua_islightuserdata(long this_addr, int index);

    public static native int internal_native_x_lua_isnil(long this_addr, int index);

    public static native int internal_native_x_lua_isnone(long this_addr, int index);

    public static native int internal_native_x_lua_isnoneornil(long this_addr, int index);

    public static native int internal_native_x_lua_isnumber(long this_addr, int index);

    public static native int internal_native_x_lua_isstring(long this_addr, int index);

    public static native int internal_native_x_lua_istable(long this_addr, int index);

    public static native int internal_native_x_lua_isthread(long this_addr, int index);

    public static native int internal_native_x_lua_isuserdata(long this_addr, int index);

    public static native int internal_native_x_lua_isyieldable(long this_addr);

    public static native void internal_native_x_lua_len(long this_addr, int index);

    public static native void internal_native_x_lua_newtable(long this_addr);

    public static native long internal_native_x_lua_newuserdatauv_addr(long this_addr, int size, int nuvalue);

    public static native int internal_native_x_lua_next(long this_addr, int index);

    public static native void internal_native_x_lua_call(long this_addr, int nargs, int nresults);

    public static native int internal_native_x_lua_pcall(long this_addr, int nargs, int nresults, int msgh);

    public static native void internal_native_x_lua_pop(long this_addr, int n);

    public static native void internal_native_x_lua_pushboolean(long this_addr, int b);

    public static native void internal_native_x_lua_pushcclosure(long this_addr, long callback_addr, int n);

    public static native void internal_native_x_lua_pushcfunction(long this_addr, long callback_addr);

    public static native long internal_native_x_lua_pushfstring_addr(long this_addr, String fmt);

    public static native void internal_native_x_lua_pushglobaltable(long this_addr);

    public static native void internal_native_x_lua_pushinteger(long this_addr, int n);

    public static native void internal_native_x_lua_pushlightuserdata(long this_addr, long n_addr);

    public static native long internal_native_x_lua_pushlstring_addr(long this_addr, String s, int len);

    public static native void internal_native_x_lua_pushnil(long this_addr);

    public static native void internal_native_x_lua_pushnumber(long this_addr, double n);

    public static native void internal_native_x_lua_pushstring(long this_addr, String s);

    public static native int internal_native_x_lua_pushthread(long this_addr);

    public static native void internal_native_x_lua_pushvalue(long this_addr, int index);

    public static native int internal_native_x_lua_rawequal(long this_addr, int index1, int index2);

    public static native int internal_native_x_lua_rawget(long this_addr, int index);

    public static native int internal_native_x_lua_rawgeti(long this_addr, int index, int n);

    public static native void internal_native_x_lua_rawset(long this_addr, int index);

    public static native void internal_native_x_lua_rawseti(long this_addr, int index, int i);

    public static native void internal_native_x_lua_remove(long this_addr, int index);

    public static native void internal_native_x_lua_replace(long this_addr, int index);

    public static native int internal_native_x_lua_resetthread(long this_addr, int index);

    public static native void internal_native_x_lua_rotate(long this_addr, int index, int n);

    public static native void internal_native_x_lua_setfield(long this_addr, int index, String k);

    public static native void internal_native_x_lua_setglobal(long this_addr, String name);

    public static native void internal_native_x_lua_seti(long this_addr, int index, int n);

    public static native int internal_native_x_lua_setuservalue(long this_addr, int index);

    public static native int internal_native_x_lua_setiuservalue(long this_addr, int index, int n);

    public static native int internal_native_x_lua_setmetatable(long this_addr, int index);

    public static native void internal_native_x_lua_settable(long this_addr, int index);

    public static native void internal_native_x_lua_settop(long this_addr, int index);

    public static native int internal_native_x_lua_status(long this_addr);

    public static native int internal_native_x_lua_stringtonumber(long this_addr, String s);

    public static native int internal_native_x_lua_toboolean(long this_addr, int index);

    public static native void internal_native_x_lua_toclose(long this_addr, int index);

    public static native int internal_native_x_lua_tointeger(long this_addr, int index);

    public static native double internal_native_x_lua_tonumber(long this_addr, int index);

    public static native long internal_native_x_lua_topointer_addr(long this_addr, int index);

    public static native long internal_native_x_lua_tostring_addr(long this_addr, int index);

    public static native long internal_native_x_lua_touserdata_addr(long this_addr, int index);

    public static native int internal_native_x_lua_type(long this_addr, int index);

    public static native long internal_native_x_lua_typename_addr(long this_addr, int tp);

    public static native int internal_native_x_lua_upvalueindex(long this_addr, int i);

    public static native double internal_native_x_lua_version(long this_addr);

    public static native void internal_native_x_lua_warning(long this_addr, String msg, int tocont);

    public static native int internal_native_x_lua_yield(long this_addr, int nresults);

    public static native int internal_native_x_luaL_loadstring(long this_addr, String s);

    public static native void internal_native_x_luaL_error(long this_addr, String fmt);

    public static native void internal_native_x_luaL_argerror(long this_addr, int arg, String extramsg);

    public static native void internal_native_x_luaL_checkversion(long this_addr);

    public static native int internal_native_x_luaL_newmetatable(long this_addr, String tname);

    public static native int internal_native_x_luaL_getmetafield(long this_addr, int obj, String fieldName);

    public static native int internal_native_x_luaL_getmetatable(long this_addr, String tname);

    public static native int internal_native_x_luaL_getsubtable(long this_addr, int idx, String fname);

    public static native int internal_native_x_luaL_len(long this_addr, int index);

    public static native void internal_native_x_luaL_pushfail(long this_addr);

    public static native int internal_native_x_luaL_ref(long this_addr, int t);

    public static native void internal_native_x_luaL_unref(long this_addr, int t, int ref);

    public static native int internal_native_x_luaL_typeerror(long this_addr, int arg, String tname);

    public static native void internal_native_createContext(long this_addr);

    public static native void internal_native_destroyContext(long this_addr);

    public static native long internal_native_dumpStack_addr(long this_addr);

    public static native long internal_native_dumpTable_addr(long this_addr);

    public static native void internal_native_setIntToVoid(long pointer_addr, int value);

    public static native int internal_native_getIntFromVoid(long pointer_addr);
}
