/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package lua;

import com.github.xpenatan.jParser.api.NativeObject;

public class LuaFunction extends NativeObject {

    static private LuaState LuaState_TEMP_STATIC_GEN_0;

    static public final LuaFunction NULL = LuaFunction.native_new();

    @Deprecated()
    protected LuaFunction(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static LuaFunction native_new() {
        return new LuaFunction((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    public static void internal_native_deleteNative(long this_addr) {
        lua.natives.JNI_LuaFunction.internal_native_deleteNative(this_addr);
    }

    public LuaFunction() {
        long addr = internal_native_create_addr();
        internal_reset(addr, true);
        setupCallback();
    }

    private void setupCallback() {
        internal_native_setupCallback(native_address);
    }

    protected int onCall(LuaState luaState) {
        return 0;
    }

    private int internal_onCall(long luaState_addr) {
        if (LuaState_TEMP_STATIC_GEN_0 == null)
            LuaState_TEMP_STATIC_GEN_0 = LuaState.native_new();
        LuaState_TEMP_STATIC_GEN_0.internal_reset(luaState_addr, false);
        return onCall(LuaState_TEMP_STATIC_GEN_0);
    }

    public static long internal_native_create_addr() {
        return lua.natives.JNI_LuaFunction.internal_native_create_addr();
    }

    public native void internal_native_setupCallback(long this_addr);
}
