/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package lua;

import com.github.xpenatan.jParser.api.NativeObject;
import com.github.xpenatan.jparser.runtime.helper.NativeString;

public class LuaState extends NativeObject {

    private NativeObject NativeObject_TEMP_GEN_0;

    private NativeString NativeString_TEMP_GEN_0;

    private NativeString NativeString_TEMP_GEN_1;

    private NativeObject NativeObject_TEMP_GEN_1;

    private NativeString NativeString_TEMP_GEN_2;

    private NativeObject NativeObject_TEMP_GEN_2;

    private NativeString NativeString_TEMP_GEN_3;

    private NativeString NativeString_TEMP_GEN_4;

    private NativeString NativeString_TEMP_GEN_5;

    static public final LuaState NULL = LuaState.native_new();

    public LuaState() {
        long addr = internal_native_create_addr();
        internal_reset(addr, true);
    }

    public static long internal_native_create_addr() {
        return lua.natives.JNI_LuaState.internal_native_create_addr();
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected LuaState(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static LuaState native_new() {
        return new LuaState((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    public static void internal_native_deleteNative(long this_addr) {
        lua.natives.JNI_LuaState.internal_native_deleteNative(this_addr);
    }

    public void lua_absindex(int idx) {
        internal_native_x_lua_absindex(native_address, idx);
    }

    public static void internal_native_x_lua_absindex(long this_addr, int idx) {
        lua.natives.JNI_LuaState.internal_native_x_lua_absindex(this_addr, idx);
    }

    public void lua_arith(int op) {
        internal_native_x_lua_arith(native_address, op);
    }

    public static void internal_native_x_lua_arith(long this_addr, int op) {
        lua.natives.JNI_LuaState.internal_native_x_lua_arith(this_addr, op);
    }

    public int lua_checkstack(int n) {
        return internal_native_x_lua_checkstack(native_address, n);
    }

    public static int internal_native_x_lua_checkstack(long this_addr, int n) {
        return lua.natives.JNI_LuaState.internal_native_x_lua_checkstack(this_addr, n);
    }

    public int lua_compare(int index1, int index2, int op) {
        return internal_native_x_lua_compare(native_address, index1, index2, op);
    }

    public static int internal_native_x_lua_compare(long this_addr, int index1, int index2, int op) {
        return lua.natives.JNI_LuaState.internal_native_x_lua_compare(this_addr, index1, index2, op);
    }

    public void lua_concat(int op, int n) {
        internal_native_x_lua_concat(native_address, op, n);
    }

    public static void internal_native_x_lua_concat(long this_addr, int op, int n) {
        lua.natives.JNI_LuaState.internal_native_x_lua_concat(this_addr, op, n);
    }

    public void lua_copy(int fromidx, int toidx) {
        internal_native_x_lua_copy(native_address, fromidx, toidx);
    }

    public static void internal_native_x_lua_copy(long this_addr, int fromidx, int toidx) {
        lua.natives.JNI_LuaState.internal_native_x_lua_copy(this_addr, fromidx, toidx);
    }

    public void lua_createtable(int narr, int nrec) {
        internal_native_x_lua_createtable(native_address, narr, nrec);
    }

    public static void internal_native_x_lua_createtable(long this_addr, int narr, int nrec) {
        lua.natives.JNI_LuaState.internal_native_x_lua_createtable(this_addr, narr, nrec);
    }

    public int lua_getfield(int index, String k) {
        return internal_native_x_lua_getfield(native_address, index, k);
    }

    public static int internal_native_x_lua_getfield(long this_addr, int index, String k) {
        return lua.natives.JNI_LuaState.internal_native_x_lua_getfield(this_addr, index, k);
    }

    public int lua_getglobal(String name) {
        return internal_native_x_lua_getglobal(native_address, name);
    }

    public static int internal_native_x_lua_getglobal(long this_addr, String name) {
        return lua.natives.JNI_LuaState.internal_native_x_lua_getglobal(this_addr, name);
    }

    public int lua_geti(int index, int i) {
        return internal_native_x_lua_geti(native_address, index, i);
    }

    public static int internal_native_x_lua_geti(long this_addr, int index, int i) {
        return lua.natives.JNI_LuaState.internal_native_x_lua_geti(this_addr, index, i);
    }

    public int lua_getmetatable(int index) {
        return internal_native_x_lua_getmetatable(native_address, index);
    }

    public static int internal_native_x_lua_getmetatable(long this_addr, int index) {
        return lua.natives.JNI_LuaState.internal_native_x_lua_getmetatable(this_addr, index);
    }

    public int lua_gettable(int index) {
        return internal_native_x_lua_gettable(native_address, index);
    }

    public static int internal_native_x_lua_gettable(long this_addr, int index) {
        return lua.natives.JNI_LuaState.internal_native_x_lua_gettable(this_addr, index);
    }

    public int lua_gettop() {
        return internal_native_x_lua_gettop(native_address);
    }

    public static int internal_native_x_lua_gettop(long this_addr) {
        return lua.natives.JNI_LuaState.internal_native_x_lua_gettop(this_addr);
    }

    public int lua_getiuservalue(int index, int n) {
        return internal_native_x_lua_getiuservalue(native_address, index, n);
    }

    public static int internal_native_x_lua_getiuservalue(long this_addr, int index, int n) {
        return lua.natives.JNI_LuaState.internal_native_x_lua_getiuservalue(this_addr, index, n);
    }

    public void lua_insert(int index) {
        internal_native_x_lua_insert(native_address, index);
    }

    public static void internal_native_x_lua_insert(long this_addr, int index) {
        lua.natives.JNI_LuaState.internal_native_x_lua_insert(this_addr, index);
    }

    public int lua_isboolean(int index) {
        return internal_native_x_lua_isboolean(native_address, index);
    }

    public static int internal_native_x_lua_isboolean(long this_addr, int index) {
        return lua.natives.JNI_LuaState.internal_native_x_lua_isboolean(this_addr, index);
    }

    public int lua_iscfunction(int index) {
        return internal_native_x_lua_iscfunction(native_address, index);
    }

    public static int internal_native_x_lua_iscfunction(long this_addr, int index) {
        return lua.natives.JNI_LuaState.internal_native_x_lua_iscfunction(this_addr, index);
    }

    public int lua_isfunction(int index) {
        return internal_native_x_lua_isfunction(native_address, index);
    }

    public static int internal_native_x_lua_isfunction(long this_addr, int index) {
        return lua.natives.JNI_LuaState.internal_native_x_lua_isfunction(this_addr, index);
    }

    public int lua_isinteger(int index) {
        return internal_native_x_lua_isinteger(native_address, index);
    }

    public static int internal_native_x_lua_isinteger(long this_addr, int index) {
        return lua.natives.JNI_LuaState.internal_native_x_lua_isinteger(this_addr, index);
    }

    public int lua_islightuserdata(int index) {
        return internal_native_x_lua_islightuserdata(native_address, index);
    }

    public static int internal_native_x_lua_islightuserdata(long this_addr, int index) {
        return lua.natives.JNI_LuaState.internal_native_x_lua_islightuserdata(this_addr, index);
    }

    public int lua_isnil(int index) {
        return internal_native_x_lua_isnil(native_address, index);
    }

    public static int internal_native_x_lua_isnil(long this_addr, int index) {
        return lua.natives.JNI_LuaState.internal_native_x_lua_isnil(this_addr, index);
    }

    public int lua_isnone(int index) {
        return internal_native_x_lua_isnone(native_address, index);
    }

    public static int internal_native_x_lua_isnone(long this_addr, int index) {
        return lua.natives.JNI_LuaState.internal_native_x_lua_isnone(this_addr, index);
    }

    public int lua_isnoneornil(int index) {
        return internal_native_x_lua_isnoneornil(native_address, index);
    }

    public static int internal_native_x_lua_isnoneornil(long this_addr, int index) {
        return lua.natives.JNI_LuaState.internal_native_x_lua_isnoneornil(this_addr, index);
    }

    public int lua_isnumber(int index) {
        return internal_native_x_lua_isnumber(native_address, index);
    }

    public static int internal_native_x_lua_isnumber(long this_addr, int index) {
        return lua.natives.JNI_LuaState.internal_native_x_lua_isnumber(this_addr, index);
    }

    public int lua_isstring(int index) {
        return internal_native_x_lua_isstring(native_address, index);
    }

    public static int internal_native_x_lua_isstring(long this_addr, int index) {
        return lua.natives.JNI_LuaState.internal_native_x_lua_isstring(this_addr, index);
    }

    public int lua_istable(int index) {
        return internal_native_x_lua_istable(native_address, index);
    }

    public static int internal_native_x_lua_istable(long this_addr, int index) {
        return lua.natives.JNI_LuaState.internal_native_x_lua_istable(this_addr, index);
    }

    public int lua_isthread(int index) {
        return internal_native_x_lua_isthread(native_address, index);
    }

    public static int internal_native_x_lua_isthread(long this_addr, int index) {
        return lua.natives.JNI_LuaState.internal_native_x_lua_isthread(this_addr, index);
    }

    public int lua_isuserdata(int index) {
        return internal_native_x_lua_isuserdata(native_address, index);
    }

    public static int internal_native_x_lua_isuserdata(long this_addr, int index) {
        return lua.natives.JNI_LuaState.internal_native_x_lua_isuserdata(this_addr, index);
    }

    public int lua_isyieldable() {
        return internal_native_x_lua_isyieldable(native_address);
    }

    public static int internal_native_x_lua_isyieldable(long this_addr) {
        return lua.natives.JNI_LuaState.internal_native_x_lua_isyieldable(this_addr);
    }

    public void lua_len(int index) {
        internal_native_x_lua_len(native_address, index);
    }

    public static void internal_native_x_lua_len(long this_addr, int index) {
        lua.natives.JNI_LuaState.internal_native_x_lua_len(this_addr, index);
    }

    public void lua_newtable() {
        internal_native_x_lua_newtable(native_address);
    }

    public static void internal_native_x_lua_newtable(long this_addr) {
        lua.natives.JNI_LuaState.internal_native_x_lua_newtable(this_addr);
    }

    public NativeObject lua_newuserdatauv(int size, int nuvalue) {
        long addr = internal_native_x_lua_newuserdatauv_addr(native_address, size, nuvalue);
        if (addr == 0)
            return NativeObject.NULL;
        if (NativeObject_TEMP_GEN_0 == null)
            NativeObject_TEMP_GEN_0 = NativeObject.native_new();
        NativeObject_TEMP_GEN_0.internal_reset(addr, false);
        return NativeObject_TEMP_GEN_0;
    }

    public static long internal_native_x_lua_newuserdatauv_addr(long this_addr, int size, int nuvalue) {
        return lua.natives.JNI_LuaState.internal_native_x_lua_newuserdatauv_addr(this_addr, size, nuvalue);
    }

    public int lua_next(int index) {
        return internal_native_x_lua_next(native_address, index);
    }

    public static int internal_native_x_lua_next(long this_addr, int index) {
        return lua.natives.JNI_LuaState.internal_native_x_lua_next(this_addr, index);
    }

    public void lua_call(int nargs, int nresults) {
        internal_native_x_lua_call(native_address, nargs, nresults);
    }

    public static void internal_native_x_lua_call(long this_addr, int nargs, int nresults) {
        lua.natives.JNI_LuaState.internal_native_x_lua_call(this_addr, nargs, nresults);
    }

    public int lua_pcall(int nargs, int nresults, int msgh) {
        return internal_native_x_lua_pcall(native_address, nargs, nresults, msgh);
    }

    public static int internal_native_x_lua_pcall(long this_addr, int nargs, int nresults, int msgh) {
        return lua.natives.JNI_LuaState.internal_native_x_lua_pcall(this_addr, nargs, nresults, msgh);
    }

    public void lua_pop(int n) {
        internal_native_x_lua_pop(native_address, n);
    }

    public static void internal_native_x_lua_pop(long this_addr, int n) {
        lua.natives.JNI_LuaState.internal_native_x_lua_pop(this_addr, n);
    }

    public void lua_pushboolean(int b) {
        internal_native_x_lua_pushboolean(native_address, b);
    }

    public static void internal_native_x_lua_pushboolean(long this_addr, int b) {
        lua.natives.JNI_LuaState.internal_native_x_lua_pushboolean(this_addr, b);
    }

    public void lua_pushcclosure(LuaFunction callback, int n) {
        internal_native_x_lua_pushcclosure(native_address, callback.native_address, n);
    }

    public static void internal_native_x_lua_pushcclosure(long this_addr, long callback_addr, int n) {
        lua.natives.JNI_LuaState.internal_native_x_lua_pushcclosure(this_addr, callback_addr, n);
    }

    public void lua_pushcfunction(LuaFunction callback) {
        internal_native_x_lua_pushcfunction(native_address, callback.native_address);
    }

    public static void internal_native_x_lua_pushcfunction(long this_addr, long callback_addr) {
        lua.natives.JNI_LuaState.internal_native_x_lua_pushcfunction(this_addr, callback_addr);
    }

    public NativeString lua_pushfstring(String fmt) {
        long addr = internal_native_x_lua_pushfstring_addr(native_address, fmt);
        if (addr == 0)
            return NativeString.NULL;
        if (NativeString_TEMP_GEN_0 == null)
            NativeString_TEMP_GEN_0 = NativeString.native_new();
        NativeString_TEMP_GEN_0.internal_reset(addr, false);
        return NativeString_TEMP_GEN_0;
    }

    public static long internal_native_x_lua_pushfstring_addr(long this_addr, String fmt) {
        return lua.natives.JNI_LuaState.internal_native_x_lua_pushfstring_addr(this_addr, fmt);
    }

    public void lua_pushglobaltable() {
        internal_native_x_lua_pushglobaltable(native_address);
    }

    public static void internal_native_x_lua_pushglobaltable(long this_addr) {
        lua.natives.JNI_LuaState.internal_native_x_lua_pushglobaltable(this_addr);
    }

    public void lua_pushinteger(int n) {
        internal_native_x_lua_pushinteger(native_address, n);
    }

    public static void internal_native_x_lua_pushinteger(long this_addr, int n) {
        lua.natives.JNI_LuaState.internal_native_x_lua_pushinteger(this_addr, n);
    }

    public void lua_pushlightuserdata(NativeObject n) {
        internal_native_x_lua_pushlightuserdata(native_address, n.native_void_address);
    }

    public static void internal_native_x_lua_pushlightuserdata(long this_addr, long n_addr) {
        lua.natives.JNI_LuaState.internal_native_x_lua_pushlightuserdata(this_addr, n_addr);
    }

    public NativeString lua_pushlstring(String s, int len) {
        long addr = internal_native_x_lua_pushlstring_addr(native_address, s, len);
        if (addr == 0)
            return NativeString.NULL;
        if (NativeString_TEMP_GEN_1 == null)
            NativeString_TEMP_GEN_1 = NativeString.native_new();
        NativeString_TEMP_GEN_1.internal_reset(addr, false);
        return NativeString_TEMP_GEN_1;
    }

    public static long internal_native_x_lua_pushlstring_addr(long this_addr, String s, int len) {
        return lua.natives.JNI_LuaState.internal_native_x_lua_pushlstring_addr(this_addr, s, len);
    }

    public void lua_pushnil() {
        internal_native_x_lua_pushnil(native_address);
    }

    public static void internal_native_x_lua_pushnil(long this_addr) {
        lua.natives.JNI_LuaState.internal_native_x_lua_pushnil(this_addr);
    }

    public void lua_pushnumber(double n) {
        internal_native_x_lua_pushnumber(native_address, n);
    }

    public static void internal_native_x_lua_pushnumber(long this_addr, double n) {
        lua.natives.JNI_LuaState.internal_native_x_lua_pushnumber(this_addr, n);
    }

    public void lua_pushstring(String s) {
        internal_native_x_lua_pushstring(native_address, s);
    }

    public static void internal_native_x_lua_pushstring(long this_addr, String s) {
        lua.natives.JNI_LuaState.internal_native_x_lua_pushstring(this_addr, s);
    }

    public int lua_pushthread() {
        return internal_native_x_lua_pushthread(native_address);
    }

    public static int internal_native_x_lua_pushthread(long this_addr) {
        return lua.natives.JNI_LuaState.internal_native_x_lua_pushthread(this_addr);
    }

    public void lua_pushvalue(int index) {
        internal_native_x_lua_pushvalue(native_address, index);
    }

    public static void internal_native_x_lua_pushvalue(long this_addr, int index) {
        lua.natives.JNI_LuaState.internal_native_x_lua_pushvalue(this_addr, index);
    }

    public int lua_rawequal(int index1, int index2) {
        return internal_native_x_lua_rawequal(native_address, index1, index2);
    }

    public static int internal_native_x_lua_rawequal(long this_addr, int index1, int index2) {
        return lua.natives.JNI_LuaState.internal_native_x_lua_rawequal(this_addr, index1, index2);
    }

    public int lua_rawget(int index) {
        return internal_native_x_lua_rawget(native_address, index);
    }

    public static int internal_native_x_lua_rawget(long this_addr, int index) {
        return lua.natives.JNI_LuaState.internal_native_x_lua_rawget(this_addr, index);
    }

    public int lua_rawgeti(int index, int n) {
        return internal_native_x_lua_rawgeti(native_address, index, n);
    }

    public static int internal_native_x_lua_rawgeti(long this_addr, int index, int n) {
        return lua.natives.JNI_LuaState.internal_native_x_lua_rawgeti(this_addr, index, n);
    }

    public void lua_rawset(int index) {
        internal_native_x_lua_rawset(native_address, index);
    }

    public static void internal_native_x_lua_rawset(long this_addr, int index) {
        lua.natives.JNI_LuaState.internal_native_x_lua_rawset(this_addr, index);
    }

    public void lua_rawseti(int index, int i) {
        internal_native_x_lua_rawseti(native_address, index, i);
    }

    public static void internal_native_x_lua_rawseti(long this_addr, int index, int i) {
        lua.natives.JNI_LuaState.internal_native_x_lua_rawseti(this_addr, index, i);
    }

    public void lua_remove(int index) {
        internal_native_x_lua_remove(native_address, index);
    }

    public static void internal_native_x_lua_remove(long this_addr, int index) {
        lua.natives.JNI_LuaState.internal_native_x_lua_remove(this_addr, index);
    }

    public void lua_replace(int index) {
        internal_native_x_lua_replace(native_address, index);
    }

    public static void internal_native_x_lua_replace(long this_addr, int index) {
        lua.natives.JNI_LuaState.internal_native_x_lua_replace(this_addr, index);
    }

    public int lua_resetthread(int index) {
        return internal_native_x_lua_resetthread(native_address, index);
    }

    public static int internal_native_x_lua_resetthread(long this_addr, int index) {
        return lua.natives.JNI_LuaState.internal_native_x_lua_resetthread(this_addr, index);
    }

    public void lua_rotate(int index, int n) {
        internal_native_x_lua_rotate(native_address, index, n);
    }

    public static void internal_native_x_lua_rotate(long this_addr, int index, int n) {
        lua.natives.JNI_LuaState.internal_native_x_lua_rotate(this_addr, index, n);
    }

    public void lua_setfield(int index, String k) {
        internal_native_x_lua_setfield(native_address, index, k);
    }

    public static void internal_native_x_lua_setfield(long this_addr, int index, String k) {
        lua.natives.JNI_LuaState.internal_native_x_lua_setfield(this_addr, index, k);
    }

    public void lua_setglobal(String name) {
        internal_native_x_lua_setglobal(native_address, name);
    }

    public static void internal_native_x_lua_setglobal(long this_addr, String name) {
        lua.natives.JNI_LuaState.internal_native_x_lua_setglobal(this_addr, name);
    }

    public void lua_seti(int index, int n) {
        internal_native_x_lua_seti(native_address, index, n);
    }

    public static void internal_native_x_lua_seti(long this_addr, int index, int n) {
        lua.natives.JNI_LuaState.internal_native_x_lua_seti(this_addr, index, n);
    }

    public int lua_setuservalue(int index) {
        return internal_native_x_lua_setuservalue(native_address, index);
    }

    public static int internal_native_x_lua_setuservalue(long this_addr, int index) {
        return lua.natives.JNI_LuaState.internal_native_x_lua_setuservalue(this_addr, index);
    }

    public int lua_setiuservalue(int index, int n) {
        return internal_native_x_lua_setiuservalue(native_address, index, n);
    }

    public static int internal_native_x_lua_setiuservalue(long this_addr, int index, int n) {
        return lua.natives.JNI_LuaState.internal_native_x_lua_setiuservalue(this_addr, index, n);
    }

    public int lua_setmetatable(int index) {
        return internal_native_x_lua_setmetatable(native_address, index);
    }

    public static int internal_native_x_lua_setmetatable(long this_addr, int index) {
        return lua.natives.JNI_LuaState.internal_native_x_lua_setmetatable(this_addr, index);
    }

    public void lua_settable(int index) {
        internal_native_x_lua_settable(native_address, index);
    }

    public static void internal_native_x_lua_settable(long this_addr, int index) {
        lua.natives.JNI_LuaState.internal_native_x_lua_settable(this_addr, index);
    }

    public void lua_settop(int index) {
        internal_native_x_lua_settop(native_address, index);
    }

    public static void internal_native_x_lua_settop(long this_addr, int index) {
        lua.natives.JNI_LuaState.internal_native_x_lua_settop(this_addr, index);
    }

    public int lua_status() {
        return internal_native_x_lua_status(native_address);
    }

    public static int internal_native_x_lua_status(long this_addr) {
        return lua.natives.JNI_LuaState.internal_native_x_lua_status(this_addr);
    }

    public int lua_stringtonumber(String s) {
        return internal_native_x_lua_stringtonumber(native_address, s);
    }

    public static int internal_native_x_lua_stringtonumber(long this_addr, String s) {
        return lua.natives.JNI_LuaState.internal_native_x_lua_stringtonumber(this_addr, s);
    }

    public int lua_toboolean(int index) {
        return internal_native_x_lua_toboolean(native_address, index);
    }

    public static int internal_native_x_lua_toboolean(long this_addr, int index) {
        return lua.natives.JNI_LuaState.internal_native_x_lua_toboolean(this_addr, index);
    }

    public void lua_toclose(int index) {
        internal_native_x_lua_toclose(native_address, index);
    }

    public static void internal_native_x_lua_toclose(long this_addr, int index) {
        lua.natives.JNI_LuaState.internal_native_x_lua_toclose(this_addr, index);
    }

    public int lua_tointeger(int index) {
        return internal_native_x_lua_tointeger(native_address, index);
    }

    public static int internal_native_x_lua_tointeger(long this_addr, int index) {
        return lua.natives.JNI_LuaState.internal_native_x_lua_tointeger(this_addr, index);
    }

    public double lua_tonumber(int index) {
        return internal_native_x_lua_tonumber(native_address, index);
    }

    public static double internal_native_x_lua_tonumber(long this_addr, int index) {
        return lua.natives.JNI_LuaState.internal_native_x_lua_tonumber(this_addr, index);
    }

    public NativeObject lua_topointer(int index) {
        long addr = internal_native_x_lua_topointer_addr(native_address, index);
        if (addr == 0)
            return NativeObject.NULL;
        if (NativeObject_TEMP_GEN_1 == null)
            NativeObject_TEMP_GEN_1 = NativeObject.native_new();
        NativeObject_TEMP_GEN_1.internal_reset(addr, false);
        return NativeObject_TEMP_GEN_1;
    }

    public static long internal_native_x_lua_topointer_addr(long this_addr, int index) {
        return lua.natives.JNI_LuaState.internal_native_x_lua_topointer_addr(this_addr, index);
    }

    public NativeString lua_tostring(int index) {
        long addr = internal_native_x_lua_tostring_addr(native_address, index);
        if (addr == 0)
            return NativeString.NULL;
        if (NativeString_TEMP_GEN_2 == null)
            NativeString_TEMP_GEN_2 = NativeString.native_new();
        NativeString_TEMP_GEN_2.internal_reset(addr, false);
        return NativeString_TEMP_GEN_2;
    }

    public static long internal_native_x_lua_tostring_addr(long this_addr, int index) {
        return lua.natives.JNI_LuaState.internal_native_x_lua_tostring_addr(this_addr, index);
    }

    public NativeObject lua_touserdata(int index) {
        long addr = internal_native_x_lua_touserdata_addr(native_address, index);
        if (addr == 0)
            return NativeObject.NULL;
        if (NativeObject_TEMP_GEN_2 == null)
            NativeObject_TEMP_GEN_2 = NativeObject.native_new();
        NativeObject_TEMP_GEN_2.internal_reset(addr, false);
        return NativeObject_TEMP_GEN_2;
    }

    public static long internal_native_x_lua_touserdata_addr(long this_addr, int index) {
        return lua.natives.JNI_LuaState.internal_native_x_lua_touserdata_addr(this_addr, index);
    }

    public int lua_type(int index) {
        return internal_native_x_lua_type(native_address, index);
    }

    public static int internal_native_x_lua_type(long this_addr, int index) {
        return lua.natives.JNI_LuaState.internal_native_x_lua_type(this_addr, index);
    }

    public NativeString lua_typename(int tp) {
        long addr = internal_native_x_lua_typename_addr(native_address, tp);
        if (addr == 0)
            return NativeString.NULL;
        if (NativeString_TEMP_GEN_3 == null)
            NativeString_TEMP_GEN_3 = NativeString.native_new();
        NativeString_TEMP_GEN_3.internal_reset(addr, false);
        return NativeString_TEMP_GEN_3;
    }

    public static long internal_native_x_lua_typename_addr(long this_addr, int tp) {
        return lua.natives.JNI_LuaState.internal_native_x_lua_typename_addr(this_addr, tp);
    }

    public int lua_upvalueindex(int i) {
        return internal_native_x_lua_upvalueindex(native_address, i);
    }

    public static int internal_native_x_lua_upvalueindex(long this_addr, int i) {
        return lua.natives.JNI_LuaState.internal_native_x_lua_upvalueindex(this_addr, i);
    }

    public double lua_version() {
        return internal_native_x_lua_version(native_address);
    }

    public static double internal_native_x_lua_version(long this_addr) {
        return lua.natives.JNI_LuaState.internal_native_x_lua_version(this_addr);
    }

    public void lua_warning(String msg, int tocont) {
        internal_native_x_lua_warning(native_address, msg, tocont);
    }

    public static void internal_native_x_lua_warning(long this_addr, String msg, int tocont) {
        lua.natives.JNI_LuaState.internal_native_x_lua_warning(this_addr, msg, tocont);
    }

    public int lua_yield(int nresults) {
        return internal_native_x_lua_yield(native_address, nresults);
    }

    public static int internal_native_x_lua_yield(long this_addr, int nresults) {
        return lua.natives.JNI_LuaState.internal_native_x_lua_yield(this_addr, nresults);
    }

    public int luaL_loadstring(String s) {
        return internal_native_x_luaL_loadstring(native_address, s);
    }

    public static int internal_native_x_luaL_loadstring(long this_addr, String s) {
        return lua.natives.JNI_LuaState.internal_native_x_luaL_loadstring(this_addr, s);
    }

    public void luaL_error(String fmt) {
        internal_native_x_luaL_error(native_address, fmt);
    }

    public static void internal_native_x_luaL_error(long this_addr, String fmt) {
        lua.natives.JNI_LuaState.internal_native_x_luaL_error(this_addr, fmt);
    }

    public void luaL_argerror(int arg, String extramsg) {
        internal_native_x_luaL_argerror(native_address, arg, extramsg);
    }

    public static void internal_native_x_luaL_argerror(long this_addr, int arg, String extramsg) {
        lua.natives.JNI_LuaState.internal_native_x_luaL_argerror(this_addr, arg, extramsg);
    }

    public void luaL_checkversion() {
        internal_native_x_luaL_checkversion(native_address);
    }

    public static void internal_native_x_luaL_checkversion(long this_addr) {
        lua.natives.JNI_LuaState.internal_native_x_luaL_checkversion(this_addr);
    }

    public int luaL_newmetatable(String tname) {
        return internal_native_x_luaL_newmetatable(native_address, tname);
    }

    public static int internal_native_x_luaL_newmetatable(long this_addr, String tname) {
        return lua.natives.JNI_LuaState.internal_native_x_luaL_newmetatable(this_addr, tname);
    }

    public int luaL_getmetafield(int obj, String fieldName) {
        return internal_native_x_luaL_getmetafield(native_address, obj, fieldName);
    }

    public static int internal_native_x_luaL_getmetafield(long this_addr, int obj, String fieldName) {
        return lua.natives.JNI_LuaState.internal_native_x_luaL_getmetafield(this_addr, obj, fieldName);
    }

    public int luaL_getmetatable(String tname) {
        return internal_native_x_luaL_getmetatable(native_address, tname);
    }

    public static int internal_native_x_luaL_getmetatable(long this_addr, String tname) {
        return lua.natives.JNI_LuaState.internal_native_x_luaL_getmetatable(this_addr, tname);
    }

    public int luaL_getsubtable(int idx, String fname) {
        return internal_native_x_luaL_getsubtable(native_address, idx, fname);
    }

    public static int internal_native_x_luaL_getsubtable(long this_addr, int idx, String fname) {
        return lua.natives.JNI_LuaState.internal_native_x_luaL_getsubtable(this_addr, idx, fname);
    }

    public int luaL_len(int index) {
        return internal_native_x_luaL_len(native_address, index);
    }

    public static int internal_native_x_luaL_len(long this_addr, int index) {
        return lua.natives.JNI_LuaState.internal_native_x_luaL_len(this_addr, index);
    }

    public void luaL_pushfail() {
        internal_native_x_luaL_pushfail(native_address);
    }

    public static void internal_native_x_luaL_pushfail(long this_addr) {
        lua.natives.JNI_LuaState.internal_native_x_luaL_pushfail(this_addr);
    }

    public int luaL_ref(int t) {
        return internal_native_x_luaL_ref(native_address, t);
    }

    public static int internal_native_x_luaL_ref(long this_addr, int t) {
        return lua.natives.JNI_LuaState.internal_native_x_luaL_ref(this_addr, t);
    }

    public void luaL_unref(int t, int ref) {
        internal_native_x_luaL_unref(native_address, t, ref);
    }

    public static void internal_native_x_luaL_unref(long this_addr, int t, int ref) {
        lua.natives.JNI_LuaState.internal_native_x_luaL_unref(this_addr, t, ref);
    }

    public int luaL_typeerror(int arg, String tname) {
        return internal_native_x_luaL_typeerror(native_address, arg, tname);
    }

    public static int internal_native_x_luaL_typeerror(long this_addr, int arg, String tname) {
        return lua.natives.JNI_LuaState.internal_native_x_luaL_typeerror(this_addr, arg, tname);
    }

    public void createContext() {
        internal_native_createContext(native_address);
    }

    public static void internal_native_createContext(long this_addr) {
        lua.natives.JNI_LuaState.internal_native_createContext(this_addr);
    }

    public void destroyContext() {
        internal_native_destroyContext(native_address);
    }

    public static void internal_native_destroyContext(long this_addr) {
        lua.natives.JNI_LuaState.internal_native_destroyContext(this_addr);
    }

    public NativeString dumpStack() {
        long addr = internal_native_dumpStack_addr(native_address);
        if (addr == 0)
            return NativeString.NULL;
        if (NativeString_TEMP_GEN_4 == null)
            NativeString_TEMP_GEN_4 = NativeString.native_new();
        NativeString_TEMP_GEN_4.internal_reset(addr, false);
        return NativeString_TEMP_GEN_4;
    }

    public static long internal_native_dumpStack_addr(long this_addr) {
        return lua.natives.JNI_LuaState.internal_native_dumpStack_addr(this_addr);
    }

    public NativeString dumpTable() {
        long addr = internal_native_dumpTable_addr(native_address);
        if (addr == 0)
            return NativeString.NULL;
        if (NativeString_TEMP_GEN_5 == null)
            NativeString_TEMP_GEN_5 = NativeString.native_new();
        NativeString_TEMP_GEN_5.internal_reset(addr, false);
        return NativeString_TEMP_GEN_5;
    }

    public static long internal_native_dumpTable_addr(long this_addr) {
        return lua.natives.JNI_LuaState.internal_native_dumpTable_addr(this_addr);
    }

    public static void setIntToVoid(NativeObject pointer, int value) {
        internal_native_setIntToVoid(pointer.native_void_address, value);
    }

    public static void internal_native_setIntToVoid(long pointer_addr, int value) {
        lua.natives.JNI_LuaState.internal_native_setIntToVoid(pointer_addr, value);
    }

    public static int getIntFromVoid(NativeObject pointer) {
        return internal_native_getIntFromVoid(pointer.native_void_address);
    }

    public static int internal_native_getIntFromVoid(long pointer_addr) {
        return lua.natives.JNI_LuaState.internal_native_getIntFromVoid(pointer_addr);
    }
}
