/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package lua;

import com.github.xpenatan.jParser.api.NativeObject;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.ValueLayout;
import java.lang.foreign.Linker;
import java.lang.foreign.SymbolLookup;
import java.lang.foreign.Arena;
import java.lang.foreign.MemorySegment;
import java.lang.invoke.MethodHandle;

public class LuaFunction extends NativeObject {

    static private LuaState LuaState_TEMP_STATIC_GEN_0;

    private static final java.lang.invoke.MethodHandles.Lookup callbackLookup = java.lang.invoke.MethodHandles.lookup();

    private static final java.lang.foreign.Linker callbackLinker = java.lang.foreign.Linker.nativeLinker();

    private static final java.lang.invoke.MethodType callbackMethodType_onCall = java.lang.invoke.MethodType.methodType(int.class, long.class);

    private static final java.lang.foreign.FunctionDescriptor callbackDescriptor_onCall = java.lang.foreign.FunctionDescriptor.of(java.lang.foreign.ValueLayout.JAVA_INT, java.lang.foreign.ValueLayout.JAVA_LONG);

    static public final LuaFunction NULL = LuaFunction.native_new();

    @Deprecated()
    protected LuaFunction(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static LuaFunction native_new() {
        return new LuaFunction((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
        releaseUpcallResources();
    }

    public static void internal_native_deleteNative(long this_addr) {
        try {
            FFMHandles.internal_native_deleteNative__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public LuaFunction() {
        long addr = internal_native_create_addr();
        internal_reset(addr, true);
        setupCallback();
    }

    private void setupCallback() {
        try {
            releaseUpcallResources();
            upcallArena = java.lang.foreign.Arena.ofShared();
            java.lang.invoke.MethodHandle mh_onCall = callbackLookup.findVirtual(LuaFunction.class, "internal_onCall", callbackMethodType_onCall).bindTo(this);
            upcallStub_onCall = callbackLinker.upcallStub(mh_onCall, callbackDescriptor_onCall, upcallArena);
            internal_native_setupCallback(native_address, upcallStub_onCall.address());
        } catch (Throwable e) {
            throw new RuntimeException(e);
        }
    }

    protected int onCall(LuaState luaState) {
        return 0;
    }

    private int internal_onCall(long luaState_addr) {
        if (LuaState_TEMP_STATIC_GEN_0 == null)
            LuaState_TEMP_STATIC_GEN_0 = LuaState.native_new();
        LuaState_TEMP_STATIC_GEN_0.internal_reset(luaState_addr, false);
        return onCall(LuaState_TEMP_STATIC_GEN_0);
    }

    public static long internal_native_create_addr() {
        try {
            return (long) FFMHandles.internal_native_create_addr__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private Arena upcallArena;

    private MemorySegment upcallStub_onCall;

    private void releaseUpcallResources() {
        Arena arena = upcallArena;
        upcallStub_onCall = null;
        upcallArena = null;
        if (arena != null) {
            try {
                arena.close();
            } catch (Exception ignored) {
            }
        }
    }

    public static void internal_native_setupCallback(long this_addr, long onCall_fp) {
        try {
            FFMHandles.internal_native_setupCallback__JJ.invokeExact(this_addr, onCall_fp);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static final class FFMHandles {

        static final java.lang.invoke.MethodHandle internal_native_deleteNative__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("lua_luafunction_deletenative", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_create_addr__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("lua_luafunction_create_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_setupCallback__JJ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("lua_luafunction_setupcallback", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));
    }
}
