/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package lua;

import com.github.xpenatan.jParser.api.NativeObject;
import com.github.xpenatan.jparser.runtime.helper.NativeString;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.ValueLayout;
import java.lang.foreign.Linker;
import java.lang.foreign.SymbolLookup;
import java.lang.foreign.Arena;
import java.lang.foreign.MemorySegment;
import java.lang.invoke.MethodHandle;

public class LuaState extends NativeObject {

    private NativeObject NativeObject_TEMP_GEN_0;

    private NativeString NativeString_TEMP_GEN_0;

    private NativeString NativeString_TEMP_GEN_1;

    private NativeObject NativeObject_TEMP_GEN_1;

    private NativeString NativeString_TEMP_GEN_2;

    private NativeObject NativeObject_TEMP_GEN_2;

    private NativeString NativeString_TEMP_GEN_3;

    private NativeString NativeString_TEMP_GEN_4;

    private NativeString NativeString_TEMP_GEN_5;

    static public final LuaState NULL = LuaState.native_new();

    public LuaState() {
        long addr = internal_native_create_addr();
        internal_reset(addr, true);
    }

    public static long internal_native_create_addr() {
        try {
            return (long) FFMHandles.internal_native_create_addr__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected LuaState(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static LuaState native_new() {
        return new LuaState((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    public static void internal_native_deleteNative(long this_addr) {
        try {
            FFMHandles.internal_native_deleteNative__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void lua_absindex(int idx) {
        internal_native_x_lua_absindex(native_address, idx);
    }

    public static void internal_native_x_lua_absindex(long this_addr, int idx) {
        try {
            FFMHandles.internal_native_x_lua_absindex__JI.invokeExact(this_addr, idx);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void lua_arith(int op) {
        internal_native_x_lua_arith(native_address, op);
    }

    public static void internal_native_x_lua_arith(long this_addr, int op) {
        try {
            FFMHandles.internal_native_x_lua_arith__JI.invokeExact(this_addr, op);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public int lua_checkstack(int n) {
        return internal_native_x_lua_checkstack(native_address, n);
    }

    public static int internal_native_x_lua_checkstack(long this_addr, int n) {
        try {
            return (int) FFMHandles.internal_native_x_lua_checkstack__JI.invokeExact(this_addr, n);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public int lua_compare(int index1, int index2, int op) {
        return internal_native_x_lua_compare(native_address, index1, index2, op);
    }

    public static int internal_native_x_lua_compare(long this_addr, int index1, int index2, int op) {
        try {
            return (int) FFMHandles.internal_native_x_lua_compare__JIII.invokeExact(this_addr, index1, index2, op);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void lua_concat(int op, int n) {
        internal_native_x_lua_concat(native_address, op, n);
    }

    public static void internal_native_x_lua_concat(long this_addr, int op, int n) {
        try {
            FFMHandles.internal_native_x_lua_concat__JII.invokeExact(this_addr, op, n);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void lua_copy(int fromidx, int toidx) {
        internal_native_x_lua_copy(native_address, fromidx, toidx);
    }

    public static void internal_native_x_lua_copy(long this_addr, int fromidx, int toidx) {
        try {
            FFMHandles.internal_native_x_lua_copy__JII.invokeExact(this_addr, fromidx, toidx);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void lua_createtable(int narr, int nrec) {
        internal_native_x_lua_createtable(native_address, narr, nrec);
    }

    public static void internal_native_x_lua_createtable(long this_addr, int narr, int nrec) {
        try {
            FFMHandles.internal_native_x_lua_createtable__JII.invokeExact(this_addr, narr, nrec);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public int lua_getfield(int index, String k) {
        return internal_native_x_lua_getfield(native_address, index, k);
    }

    public static int internal_native_x_lua_getfield(long this_addr, int index, String k) {
        try {
            return (int) FFMHandles.internal_native_x_lua_getfield__JILjava_lang_String_2.invokeExact(this_addr, index, com.github.xpenatan.jparser.runtime.helper.NativeUtils.toCString(k));
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public int lua_getglobal(String name) {
        return internal_native_x_lua_getglobal(native_address, name);
    }

    public static int internal_native_x_lua_getglobal(long this_addr, String name) {
        try {
            return (int) FFMHandles.internal_native_x_lua_getglobal__JLjava_lang_String_2.invokeExact(this_addr, com.github.xpenatan.jparser.runtime.helper.NativeUtils.toCString(name));
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public int lua_geti(int index, int i) {
        return internal_native_x_lua_geti(native_address, index, i);
    }

    public static int internal_native_x_lua_geti(long this_addr, int index, int i) {
        try {
            return (int) FFMHandles.internal_native_x_lua_geti__JII.invokeExact(this_addr, index, i);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public int lua_getmetatable(int index) {
        return internal_native_x_lua_getmetatable(native_address, index);
    }

    public static int internal_native_x_lua_getmetatable(long this_addr, int index) {
        try {
            return (int) FFMHandles.internal_native_x_lua_getmetatable__JI.invokeExact(this_addr, index);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public int lua_gettable(int index) {
        return internal_native_x_lua_gettable(native_address, index);
    }

    public static int internal_native_x_lua_gettable(long this_addr, int index) {
        try {
            return (int) FFMHandles.internal_native_x_lua_gettable__JI.invokeExact(this_addr, index);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public int lua_gettop() {
        return internal_native_x_lua_gettop(native_address);
    }

    public static int internal_native_x_lua_gettop(long this_addr) {
        try {
            return (int) FFMHandles.internal_native_x_lua_gettop__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public int lua_getiuservalue(int index, int n) {
        return internal_native_x_lua_getiuservalue(native_address, index, n);
    }

    public static int internal_native_x_lua_getiuservalue(long this_addr, int index, int n) {
        try {
            return (int) FFMHandles.internal_native_x_lua_getiuservalue__JII.invokeExact(this_addr, index, n);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void lua_insert(int index) {
        internal_native_x_lua_insert(native_address, index);
    }

    public static void internal_native_x_lua_insert(long this_addr, int index) {
        try {
            FFMHandles.internal_native_x_lua_insert__JI.invokeExact(this_addr, index);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public int lua_isboolean(int index) {
        return internal_native_x_lua_isboolean(native_address, index);
    }

    public static int internal_native_x_lua_isboolean(long this_addr, int index) {
        try {
            return (int) FFMHandles.internal_native_x_lua_isboolean__JI.invokeExact(this_addr, index);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public int lua_iscfunction(int index) {
        return internal_native_x_lua_iscfunction(native_address, index);
    }

    public static int internal_native_x_lua_iscfunction(long this_addr, int index) {
        try {
            return (int) FFMHandles.internal_native_x_lua_iscfunction__JI.invokeExact(this_addr, index);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public int lua_isfunction(int index) {
        return internal_native_x_lua_isfunction(native_address, index);
    }

    public static int internal_native_x_lua_isfunction(long this_addr, int index) {
        try {
            return (int) FFMHandles.internal_native_x_lua_isfunction__JI.invokeExact(this_addr, index);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public int lua_isinteger(int index) {
        return internal_native_x_lua_isinteger(native_address, index);
    }

    public static int internal_native_x_lua_isinteger(long this_addr, int index) {
        try {
            return (int) FFMHandles.internal_native_x_lua_isinteger__JI.invokeExact(this_addr, index);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public int lua_islightuserdata(int index) {
        return internal_native_x_lua_islightuserdata(native_address, index);
    }

    public static int internal_native_x_lua_islightuserdata(long this_addr, int index) {
        try {
            return (int) FFMHandles.internal_native_x_lua_islightuserdata__JI.invokeExact(this_addr, index);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public int lua_isnil(int index) {
        return internal_native_x_lua_isnil(native_address, index);
    }

    public static int internal_native_x_lua_isnil(long this_addr, int index) {
        try {
            return (int) FFMHandles.internal_native_x_lua_isnil__JI.invokeExact(this_addr, index);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public int lua_isnone(int index) {
        return internal_native_x_lua_isnone(native_address, index);
    }

    public static int internal_native_x_lua_isnone(long this_addr, int index) {
        try {
            return (int) FFMHandles.internal_native_x_lua_isnone__JI.invokeExact(this_addr, index);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public int lua_isnoneornil(int index) {
        return internal_native_x_lua_isnoneornil(native_address, index);
    }

    public static int internal_native_x_lua_isnoneornil(long this_addr, int index) {
        try {
            return (int) FFMHandles.internal_native_x_lua_isnoneornil__JI.invokeExact(this_addr, index);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public int lua_isnumber(int index) {
        return internal_native_x_lua_isnumber(native_address, index);
    }

    public static int internal_native_x_lua_isnumber(long this_addr, int index) {
        try {
            return (int) FFMHandles.internal_native_x_lua_isnumber__JI.invokeExact(this_addr, index);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public int lua_isstring(int index) {
        return internal_native_x_lua_isstring(native_address, index);
    }

    public static int internal_native_x_lua_isstring(long this_addr, int index) {
        try {
            return (int) FFMHandles.internal_native_x_lua_isstring__JI.invokeExact(this_addr, index);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public int lua_istable(int index) {
        return internal_native_x_lua_istable(native_address, index);
    }

    public static int internal_native_x_lua_istable(long this_addr, int index) {
        try {
            return (int) FFMHandles.internal_native_x_lua_istable__JI.invokeExact(this_addr, index);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public int lua_isthread(int index) {
        return internal_native_x_lua_isthread(native_address, index);
    }

    public static int internal_native_x_lua_isthread(long this_addr, int index) {
        try {
            return (int) FFMHandles.internal_native_x_lua_isthread__JI.invokeExact(this_addr, index);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public int lua_isuserdata(int index) {
        return internal_native_x_lua_isuserdata(native_address, index);
    }

    public static int internal_native_x_lua_isuserdata(long this_addr, int index) {
        try {
            return (int) FFMHandles.internal_native_x_lua_isuserdata__JI.invokeExact(this_addr, index);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public int lua_isyieldable() {
        return internal_native_x_lua_isyieldable(native_address);
    }

    public static int internal_native_x_lua_isyieldable(long this_addr) {
        try {
            return (int) FFMHandles.internal_native_x_lua_isyieldable__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void lua_len(int index) {
        internal_native_x_lua_len(native_address, index);
    }

    public static void internal_native_x_lua_len(long this_addr, int index) {
        try {
            FFMHandles.internal_native_x_lua_len__JI.invokeExact(this_addr, index);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void lua_newtable() {
        internal_native_x_lua_newtable(native_address);
    }

    public static void internal_native_x_lua_newtable(long this_addr) {
        try {
            FFMHandles.internal_native_x_lua_newtable__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public NativeObject lua_newuserdatauv(int size, int nuvalue) {
        long addr = internal_native_x_lua_newuserdatauv_addr(native_address, size, nuvalue);
        if (addr == 0)
            return NativeObject.NULL;
        if (NativeObject_TEMP_GEN_0 == null)
            NativeObject_TEMP_GEN_0 = NativeObject.native_new();
        NativeObject_TEMP_GEN_0.internal_reset(addr, false);
        return NativeObject_TEMP_GEN_0;
    }

    public static long internal_native_x_lua_newuserdatauv_addr(long this_addr, int size, int nuvalue) {
        try {
            return (long) FFMHandles.internal_native_x_lua_newuserdatauv_addr__JII.invokeExact(this_addr, size, nuvalue);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public int lua_next(int index) {
        return internal_native_x_lua_next(native_address, index);
    }

    public static int internal_native_x_lua_next(long this_addr, int index) {
        try {
            return (int) FFMHandles.internal_native_x_lua_next__JI.invokeExact(this_addr, index);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void lua_call(int nargs, int nresults) {
        internal_native_x_lua_call(native_address, nargs, nresults);
    }

    public static void internal_native_x_lua_call(long this_addr, int nargs, int nresults) {
        try {
            FFMHandles.internal_native_x_lua_call__JII.invokeExact(this_addr, nargs, nresults);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public int lua_pcall(int nargs, int nresults, int msgh) {
        return internal_native_x_lua_pcall(native_address, nargs, nresults, msgh);
    }

    public static int internal_native_x_lua_pcall(long this_addr, int nargs, int nresults, int msgh) {
        try {
            return (int) FFMHandles.internal_native_x_lua_pcall__JIII.invokeExact(this_addr, nargs, nresults, msgh);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void lua_pop(int n) {
        internal_native_x_lua_pop(native_address, n);
    }

    public static void internal_native_x_lua_pop(long this_addr, int n) {
        try {
            FFMHandles.internal_native_x_lua_pop__JI.invokeExact(this_addr, n);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void lua_pushboolean(int b) {
        internal_native_x_lua_pushboolean(native_address, b);
    }

    public static void internal_native_x_lua_pushboolean(long this_addr, int b) {
        try {
            FFMHandles.internal_native_x_lua_pushboolean__JI.invokeExact(this_addr, b);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void lua_pushcclosure(LuaFunction callback, int n) {
        internal_native_x_lua_pushcclosure(native_address, callback.native_address, n);
    }

    public static void internal_native_x_lua_pushcclosure(long this_addr, long callback_addr, int n) {
        try {
            FFMHandles.internal_native_x_lua_pushcclosure__JJI.invokeExact(this_addr, callback_addr, n);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void lua_pushcfunction(LuaFunction callback) {
        internal_native_x_lua_pushcfunction(native_address, callback.native_address);
    }

    public static void internal_native_x_lua_pushcfunction(long this_addr, long callback_addr) {
        try {
            FFMHandles.internal_native_x_lua_pushcfunction__JJ.invokeExact(this_addr, callback_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public NativeString lua_pushfstring(String fmt) {
        long addr = internal_native_x_lua_pushfstring_addr(native_address, fmt);
        if (addr == 0)
            return NativeString.NULL;
        if (NativeString_TEMP_GEN_0 == null)
            NativeString_TEMP_GEN_0 = NativeString.native_new();
        NativeString_TEMP_GEN_0.internal_reset(addr, false);
        return NativeString_TEMP_GEN_0;
    }

    public static long internal_native_x_lua_pushfstring_addr(long this_addr, String fmt) {
        try {
            return (long) FFMHandles.internal_native_x_lua_pushfstring_addr__JLjava_lang_String_2.invokeExact(this_addr, com.github.xpenatan.jparser.runtime.helper.NativeUtils.toCString(fmt));
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void lua_pushglobaltable() {
        internal_native_x_lua_pushglobaltable(native_address);
    }

    public static void internal_native_x_lua_pushglobaltable(long this_addr) {
        try {
            FFMHandles.internal_native_x_lua_pushglobaltable__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void lua_pushinteger(int n) {
        internal_native_x_lua_pushinteger(native_address, n);
    }

    public static void internal_native_x_lua_pushinteger(long this_addr, int n) {
        try {
            FFMHandles.internal_native_x_lua_pushinteger__JI.invokeExact(this_addr, n);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void lua_pushlightuserdata(NativeObject n) {
        internal_native_x_lua_pushlightuserdata(native_address, n.native_void_address);
    }

    public static void internal_native_x_lua_pushlightuserdata(long this_addr, long n_addr) {
        try {
            FFMHandles.internal_native_x_lua_pushlightuserdata__JJ.invokeExact(this_addr, n_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public NativeString lua_pushlstring(String s, int len) {
        long addr = internal_native_x_lua_pushlstring_addr(native_address, s, len);
        if (addr == 0)
            return NativeString.NULL;
        if (NativeString_TEMP_GEN_1 == null)
            NativeString_TEMP_GEN_1 = NativeString.native_new();
        NativeString_TEMP_GEN_1.internal_reset(addr, false);
        return NativeString_TEMP_GEN_1;
    }

    public static long internal_native_x_lua_pushlstring_addr(long this_addr, String s, int len) {
        try {
            return (long) FFMHandles.internal_native_x_lua_pushlstring_addr__JLjava_lang_String_2I.invokeExact(this_addr, com.github.xpenatan.jparser.runtime.helper.NativeUtils.toCString(s), len);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void lua_pushnil() {
        internal_native_x_lua_pushnil(native_address);
    }

    public static void internal_native_x_lua_pushnil(long this_addr) {
        try {
            FFMHandles.internal_native_x_lua_pushnil__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void lua_pushnumber(double n) {
        internal_native_x_lua_pushnumber(native_address, n);
    }

    public static void internal_native_x_lua_pushnumber(long this_addr, double n) {
        try {
            FFMHandles.internal_native_x_lua_pushnumber__JD.invokeExact(this_addr, n);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void lua_pushstring(String s) {
        internal_native_x_lua_pushstring(native_address, s);
    }

    public static void internal_native_x_lua_pushstring(long this_addr, String s) {
        try {
            FFMHandles.internal_native_x_lua_pushstring__JLjava_lang_String_2.invokeExact(this_addr, com.github.xpenatan.jparser.runtime.helper.NativeUtils.toCString(s));
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public int lua_pushthread() {
        return internal_native_x_lua_pushthread(native_address);
    }

    public static int internal_native_x_lua_pushthread(long this_addr) {
        try {
            return (int) FFMHandles.internal_native_x_lua_pushthread__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void lua_pushvalue(int index) {
        internal_native_x_lua_pushvalue(native_address, index);
    }

    public static void internal_native_x_lua_pushvalue(long this_addr, int index) {
        try {
            FFMHandles.internal_native_x_lua_pushvalue__JI.invokeExact(this_addr, index);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public int lua_rawequal(int index1, int index2) {
        return internal_native_x_lua_rawequal(native_address, index1, index2);
    }

    public static int internal_native_x_lua_rawequal(long this_addr, int index1, int index2) {
        try {
            return (int) FFMHandles.internal_native_x_lua_rawequal__JII.invokeExact(this_addr, index1, index2);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public int lua_rawget(int index) {
        return internal_native_x_lua_rawget(native_address, index);
    }

    public static int internal_native_x_lua_rawget(long this_addr, int index) {
        try {
            return (int) FFMHandles.internal_native_x_lua_rawget__JI.invokeExact(this_addr, index);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public int lua_rawgeti(int index, int n) {
        return internal_native_x_lua_rawgeti(native_address, index, n);
    }

    public static int internal_native_x_lua_rawgeti(long this_addr, int index, int n) {
        try {
            return (int) FFMHandles.internal_native_x_lua_rawgeti__JII.invokeExact(this_addr, index, n);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void lua_rawset(int index) {
        internal_native_x_lua_rawset(native_address, index);
    }

    public static void internal_native_x_lua_rawset(long this_addr, int index) {
        try {
            FFMHandles.internal_native_x_lua_rawset__JI.invokeExact(this_addr, index);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void lua_rawseti(int index, int i) {
        internal_native_x_lua_rawseti(native_address, index, i);
    }

    public static void internal_native_x_lua_rawseti(long this_addr, int index, int i) {
        try {
            FFMHandles.internal_native_x_lua_rawseti__JII.invokeExact(this_addr, index, i);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void lua_remove(int index) {
        internal_native_x_lua_remove(native_address, index);
    }

    public static void internal_native_x_lua_remove(long this_addr, int index) {
        try {
            FFMHandles.internal_native_x_lua_remove__JI.invokeExact(this_addr, index);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void lua_replace(int index) {
        internal_native_x_lua_replace(native_address, index);
    }

    public static void internal_native_x_lua_replace(long this_addr, int index) {
        try {
            FFMHandles.internal_native_x_lua_replace__JI.invokeExact(this_addr, index);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public int lua_resetthread(int index) {
        return internal_native_x_lua_resetthread(native_address, index);
    }

    public static int internal_native_x_lua_resetthread(long this_addr, int index) {
        try {
            return (int) FFMHandles.internal_native_x_lua_resetthread__JI.invokeExact(this_addr, index);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void lua_rotate(int index, int n) {
        internal_native_x_lua_rotate(native_address, index, n);
    }

    public static void internal_native_x_lua_rotate(long this_addr, int index, int n) {
        try {
            FFMHandles.internal_native_x_lua_rotate__JII.invokeExact(this_addr, index, n);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void lua_setfield(int index, String k) {
        internal_native_x_lua_setfield(native_address, index, k);
    }

    public static void internal_native_x_lua_setfield(long this_addr, int index, String k) {
        try {
            FFMHandles.internal_native_x_lua_setfield__JILjava_lang_String_2.invokeExact(this_addr, index, com.github.xpenatan.jparser.runtime.helper.NativeUtils.toCString(k));
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void lua_setglobal(String name) {
        internal_native_x_lua_setglobal(native_address, name);
    }

    public static void internal_native_x_lua_setglobal(long this_addr, String name) {
        try {
            FFMHandles.internal_native_x_lua_setglobal__JLjava_lang_String_2.invokeExact(this_addr, com.github.xpenatan.jparser.runtime.helper.NativeUtils.toCString(name));
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void lua_seti(int index, int n) {
        internal_native_x_lua_seti(native_address, index, n);
    }

    public static void internal_native_x_lua_seti(long this_addr, int index, int n) {
        try {
            FFMHandles.internal_native_x_lua_seti__JII.invokeExact(this_addr, index, n);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public int lua_setuservalue(int index) {
        return internal_native_x_lua_setuservalue(native_address, index);
    }

    public static int internal_native_x_lua_setuservalue(long this_addr, int index) {
        try {
            return (int) FFMHandles.internal_native_x_lua_setuservalue__JI.invokeExact(this_addr, index);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public int lua_setiuservalue(int index, int n) {
        return internal_native_x_lua_setiuservalue(native_address, index, n);
    }

    public static int internal_native_x_lua_setiuservalue(long this_addr, int index, int n) {
        try {
            return (int) FFMHandles.internal_native_x_lua_setiuservalue__JII.invokeExact(this_addr, index, n);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public int lua_setmetatable(int index) {
        return internal_native_x_lua_setmetatable(native_address, index);
    }

    public static int internal_native_x_lua_setmetatable(long this_addr, int index) {
        try {
            return (int) FFMHandles.internal_native_x_lua_setmetatable__JI.invokeExact(this_addr, index);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void lua_settable(int index) {
        internal_native_x_lua_settable(native_address, index);
    }

    public static void internal_native_x_lua_settable(long this_addr, int index) {
        try {
            FFMHandles.internal_native_x_lua_settable__JI.invokeExact(this_addr, index);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void lua_settop(int index) {
        internal_native_x_lua_settop(native_address, index);
    }

    public static void internal_native_x_lua_settop(long this_addr, int index) {
        try {
            FFMHandles.internal_native_x_lua_settop__JI.invokeExact(this_addr, index);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public int lua_status() {
        return internal_native_x_lua_status(native_address);
    }

    public static int internal_native_x_lua_status(long this_addr) {
        try {
            return (int) FFMHandles.internal_native_x_lua_status__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public int lua_stringtonumber(String s) {
        return internal_native_x_lua_stringtonumber(native_address, s);
    }

    public static int internal_native_x_lua_stringtonumber(long this_addr, String s) {
        try {
            return (int) FFMHandles.internal_native_x_lua_stringtonumber__JLjava_lang_String_2.invokeExact(this_addr, com.github.xpenatan.jparser.runtime.helper.NativeUtils.toCString(s));
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public int lua_toboolean(int index) {
        return internal_native_x_lua_toboolean(native_address, index);
    }

    public static int internal_native_x_lua_toboolean(long this_addr, int index) {
        try {
            return (int) FFMHandles.internal_native_x_lua_toboolean__JI.invokeExact(this_addr, index);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void lua_toclose(int index) {
        internal_native_x_lua_toclose(native_address, index);
    }

    public static void internal_native_x_lua_toclose(long this_addr, int index) {
        try {
            FFMHandles.internal_native_x_lua_toclose__JI.invokeExact(this_addr, index);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public int lua_tointeger(int index) {
        return internal_native_x_lua_tointeger(native_address, index);
    }

    public static int internal_native_x_lua_tointeger(long this_addr, int index) {
        try {
            return (int) FFMHandles.internal_native_x_lua_tointeger__JI.invokeExact(this_addr, index);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public double lua_tonumber(int index) {
        return internal_native_x_lua_tonumber(native_address, index);
    }

    public static double internal_native_x_lua_tonumber(long this_addr, int index) {
        try {
            return (double) FFMHandles.internal_native_x_lua_tonumber__JI.invokeExact(this_addr, index);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public NativeObject lua_topointer(int index) {
        long addr = internal_native_x_lua_topointer_addr(native_address, index);
        if (addr == 0)
            return NativeObject.NULL;
        if (NativeObject_TEMP_GEN_1 == null)
            NativeObject_TEMP_GEN_1 = NativeObject.native_new();
        NativeObject_TEMP_GEN_1.internal_reset(addr, false);
        return NativeObject_TEMP_GEN_1;
    }

    public static long internal_native_x_lua_topointer_addr(long this_addr, int index) {
        try {
            return (long) FFMHandles.internal_native_x_lua_topointer_addr__JI.invokeExact(this_addr, index);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public NativeString lua_tostring(int index) {
        long addr = internal_native_x_lua_tostring_addr(native_address, index);
        if (addr == 0)
            return NativeString.NULL;
        if (NativeString_TEMP_GEN_2 == null)
            NativeString_TEMP_GEN_2 = NativeString.native_new();
        NativeString_TEMP_GEN_2.internal_reset(addr, false);
        return NativeString_TEMP_GEN_2;
    }

    public static long internal_native_x_lua_tostring_addr(long this_addr, int index) {
        try {
            return (long) FFMHandles.internal_native_x_lua_tostring_addr__JI.invokeExact(this_addr, index);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public NativeObject lua_touserdata(int index) {
        long addr = internal_native_x_lua_touserdata_addr(native_address, index);
        if (addr == 0)
            return NativeObject.NULL;
        if (NativeObject_TEMP_GEN_2 == null)
            NativeObject_TEMP_GEN_2 = NativeObject.native_new();
        NativeObject_TEMP_GEN_2.internal_reset(addr, false);
        return NativeObject_TEMP_GEN_2;
    }

    public static long internal_native_x_lua_touserdata_addr(long this_addr, int index) {
        try {
            return (long) FFMHandles.internal_native_x_lua_touserdata_addr__JI.invokeExact(this_addr, index);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public int lua_type(int index) {
        return internal_native_x_lua_type(native_address, index);
    }

    public static int internal_native_x_lua_type(long this_addr, int index) {
        try {
            return (int) FFMHandles.internal_native_x_lua_type__JI.invokeExact(this_addr, index);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public NativeString lua_typename(int tp) {
        long addr = internal_native_x_lua_typename_addr(native_address, tp);
        if (addr == 0)
            return NativeString.NULL;
        if (NativeString_TEMP_GEN_3 == null)
            NativeString_TEMP_GEN_3 = NativeString.native_new();
        NativeString_TEMP_GEN_3.internal_reset(addr, false);
        return NativeString_TEMP_GEN_3;
    }

    public static long internal_native_x_lua_typename_addr(long this_addr, int tp) {
        try {
            return (long) FFMHandles.internal_native_x_lua_typename_addr__JI.invokeExact(this_addr, tp);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public int lua_upvalueindex(int i) {
        return internal_native_x_lua_upvalueindex(native_address, i);
    }

    public static int internal_native_x_lua_upvalueindex(long this_addr, int i) {
        try {
            return (int) FFMHandles.internal_native_x_lua_upvalueindex__JI.invokeExact(this_addr, i);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public double lua_version() {
        return internal_native_x_lua_version(native_address);
    }

    public static double internal_native_x_lua_version(long this_addr) {
        try {
            return (double) FFMHandles.internal_native_x_lua_version__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void lua_warning(String msg, int tocont) {
        internal_native_x_lua_warning(native_address, msg, tocont);
    }

    public static void internal_native_x_lua_warning(long this_addr, String msg, int tocont) {
        try {
            FFMHandles.internal_native_x_lua_warning__JLjava_lang_String_2I.invokeExact(this_addr, com.github.xpenatan.jparser.runtime.helper.NativeUtils.toCString(msg), tocont);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public int lua_yield(int nresults) {
        return internal_native_x_lua_yield(native_address, nresults);
    }

    public static int internal_native_x_lua_yield(long this_addr, int nresults) {
        try {
            return (int) FFMHandles.internal_native_x_lua_yield__JI.invokeExact(this_addr, nresults);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public int luaL_loadstring(String s) {
        return internal_native_x_luaL_loadstring(native_address, s);
    }

    public static int internal_native_x_luaL_loadstring(long this_addr, String s) {
        try {
            return (int) FFMHandles.internal_native_x_luaL_loadstring__JLjava_lang_String_2.invokeExact(this_addr, com.github.xpenatan.jparser.runtime.helper.NativeUtils.toCString(s));
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void luaL_error(String fmt) {
        internal_native_x_luaL_error(native_address, fmt);
    }

    public static void internal_native_x_luaL_error(long this_addr, String fmt) {
        try {
            FFMHandles.internal_native_x_luaL_error__JLjava_lang_String_2.invokeExact(this_addr, com.github.xpenatan.jparser.runtime.helper.NativeUtils.toCString(fmt));
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void luaL_argerror(int arg, String extramsg) {
        internal_native_x_luaL_argerror(native_address, arg, extramsg);
    }

    public static void internal_native_x_luaL_argerror(long this_addr, int arg, String extramsg) {
        try {
            FFMHandles.internal_native_x_luaL_argerror__JILjava_lang_String_2.invokeExact(this_addr, arg, com.github.xpenatan.jparser.runtime.helper.NativeUtils.toCString(extramsg));
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void luaL_checkversion() {
        internal_native_x_luaL_checkversion(native_address);
    }

    public static void internal_native_x_luaL_checkversion(long this_addr) {
        try {
            FFMHandles.internal_native_x_luaL_checkversion__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public int luaL_newmetatable(String tname) {
        return internal_native_x_luaL_newmetatable(native_address, tname);
    }

    public static int internal_native_x_luaL_newmetatable(long this_addr, String tname) {
        try {
            return (int) FFMHandles.internal_native_x_luaL_newmetatable__JLjava_lang_String_2.invokeExact(this_addr, com.github.xpenatan.jparser.runtime.helper.NativeUtils.toCString(tname));
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public int luaL_getmetafield(int obj, String fieldName) {
        return internal_native_x_luaL_getmetafield(native_address, obj, fieldName);
    }

    public static int internal_native_x_luaL_getmetafield(long this_addr, int obj, String fieldName) {
        try {
            return (int) FFMHandles.internal_native_x_luaL_getmetafield__JILjava_lang_String_2.invokeExact(this_addr, obj, com.github.xpenatan.jparser.runtime.helper.NativeUtils.toCString(fieldName));
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public int luaL_getmetatable(String tname) {
        return internal_native_x_luaL_getmetatable(native_address, tname);
    }

    public static int internal_native_x_luaL_getmetatable(long this_addr, String tname) {
        try {
            return (int) FFMHandles.internal_native_x_luaL_getmetatable__JLjava_lang_String_2.invokeExact(this_addr, com.github.xpenatan.jparser.runtime.helper.NativeUtils.toCString(tname));
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public int luaL_getsubtable(int idx, String fname) {
        return internal_native_x_luaL_getsubtable(native_address, idx, fname);
    }

    public static int internal_native_x_luaL_getsubtable(long this_addr, int idx, String fname) {
        try {
            return (int) FFMHandles.internal_native_x_luaL_getsubtable__JILjava_lang_String_2.invokeExact(this_addr, idx, com.github.xpenatan.jparser.runtime.helper.NativeUtils.toCString(fname));
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public int luaL_len(int index) {
        return internal_native_x_luaL_len(native_address, index);
    }

    public static int internal_native_x_luaL_len(long this_addr, int index) {
        try {
            return (int) FFMHandles.internal_native_x_luaL_len__JI.invokeExact(this_addr, index);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void luaL_pushfail() {
        internal_native_x_luaL_pushfail(native_address);
    }

    public static void internal_native_x_luaL_pushfail(long this_addr) {
        try {
            FFMHandles.internal_native_x_luaL_pushfail__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public int luaL_ref(int t) {
        return internal_native_x_luaL_ref(native_address, t);
    }

    public static int internal_native_x_luaL_ref(long this_addr, int t) {
        try {
            return (int) FFMHandles.internal_native_x_luaL_ref__JI.invokeExact(this_addr, t);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void luaL_unref(int t, int ref) {
        internal_native_x_luaL_unref(native_address, t, ref);
    }

    public static void internal_native_x_luaL_unref(long this_addr, int t, int ref) {
        try {
            FFMHandles.internal_native_x_luaL_unref__JII.invokeExact(this_addr, t, ref);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public int luaL_typeerror(int arg, String tname) {
        return internal_native_x_luaL_typeerror(native_address, arg, tname);
    }

    public static int internal_native_x_luaL_typeerror(long this_addr, int arg, String tname) {
        try {
            return (int) FFMHandles.internal_native_x_luaL_typeerror__JILjava_lang_String_2.invokeExact(this_addr, arg, com.github.xpenatan.jparser.runtime.helper.NativeUtils.toCString(tname));
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void createContext() {
        internal_native_createContext(native_address);
    }

    public static void internal_native_createContext(long this_addr) {
        try {
            FFMHandles.internal_native_createContext__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void destroyContext() {
        internal_native_destroyContext(native_address);
    }

    public static void internal_native_destroyContext(long this_addr) {
        try {
            FFMHandles.internal_native_destroyContext__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public NativeString dumpStack() {
        long addr = internal_native_dumpStack_addr(native_address);
        if (addr == 0)
            return NativeString.NULL;
        if (NativeString_TEMP_GEN_4 == null)
            NativeString_TEMP_GEN_4 = NativeString.native_new();
        NativeString_TEMP_GEN_4.internal_reset(addr, false);
        return NativeString_TEMP_GEN_4;
    }

    public static long internal_native_dumpStack_addr(long this_addr) {
        try {
            return (long) FFMHandles.internal_native_dumpStack_addr__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public NativeString dumpTable() {
        long addr = internal_native_dumpTable_addr(native_address);
        if (addr == 0)
            return NativeString.NULL;
        if (NativeString_TEMP_GEN_5 == null)
            NativeString_TEMP_GEN_5 = NativeString.native_new();
        NativeString_TEMP_GEN_5.internal_reset(addr, false);
        return NativeString_TEMP_GEN_5;
    }

    public static long internal_native_dumpTable_addr(long this_addr) {
        try {
            return (long) FFMHandles.internal_native_dumpTable_addr__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public static void setIntToVoid(NativeObject pointer, int value) {
        internal_native_setIntToVoid(pointer.native_void_address, value);
    }

    public static void internal_native_setIntToVoid(long pointer_addr, int value) {
        try {
            FFMHandles.internal_native_setIntToVoid__JI.invokeExact(pointer_addr, value);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public static int getIntFromVoid(NativeObject pointer) {
        return internal_native_getIntFromVoid(pointer.native_void_address);
    }

    public static int internal_native_getIntFromVoid(long pointer_addr) {
        try {
            return (int) FFMHandles.internal_native_getIntFromVoid__J.invokeExact(pointer_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static final class FFMHandles {

        static final java.lang.invoke.MethodHandle internal_native_create_addr__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("lua_luastate_create_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_deleteNative__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("lua_luastate_deletenative", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_x_lua_absindex__JI = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("lua_luastate_x_lua_absindex", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle internal_native_x_lua_arith__JI = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("lua_luastate_x_lua_arith", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle internal_native_x_lua_checkstack__JI = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("lua_luastate_x_lua_checkstack", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG, ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle internal_native_x_lua_compare__JIII = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("lua_luastate_x_lua_compare", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG, ValueLayout.JAVA_INT, ValueLayout.JAVA_INT, ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle internal_native_x_lua_concat__JII = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("lua_luastate_x_lua_concat", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_INT, ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle internal_native_x_lua_copy__JII = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("lua_luastate_x_lua_copy", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_INT, ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle internal_native_x_lua_createtable__JII = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("lua_luastate_x_lua_createtable", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_INT, ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle internal_native_x_lua_getfield__JILjava_lang_String_2 = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("lua_luastate_x_lua_getfield", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG, ValueLayout.JAVA_INT, ValueLayout.ADDRESS));

        static final java.lang.invoke.MethodHandle internal_native_x_lua_getglobal__JLjava_lang_String_2 = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("lua_luastate_x_lua_getglobal", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG, ValueLayout.ADDRESS));

        static final java.lang.invoke.MethodHandle internal_native_x_lua_geti__JII = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("lua_luastate_x_lua_geti", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG, ValueLayout.JAVA_INT, ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle internal_native_x_lua_getmetatable__JI = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("lua_luastate_x_lua_getmetatable", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG, ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle internal_native_x_lua_gettable__JI = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("lua_luastate_x_lua_gettable", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG, ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle internal_native_x_lua_gettop__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("lua_luastate_x_lua_gettop", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_x_lua_getiuservalue__JII = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("lua_luastate_x_lua_getiuservalue", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG, ValueLayout.JAVA_INT, ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle internal_native_x_lua_insert__JI = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("lua_luastate_x_lua_insert", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle internal_native_x_lua_isboolean__JI = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("lua_luastate_x_lua_isboolean", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG, ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle internal_native_x_lua_iscfunction__JI = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("lua_luastate_x_lua_iscfunction", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG, ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle internal_native_x_lua_isfunction__JI = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("lua_luastate_x_lua_isfunction", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG, ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle internal_native_x_lua_isinteger__JI = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("lua_luastate_x_lua_isinteger", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG, ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle internal_native_x_lua_islightuserdata__JI = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("lua_luastate_x_lua_islightuserdata", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG, ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle internal_native_x_lua_isnil__JI = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("lua_luastate_x_lua_isnil", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG, ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle internal_native_x_lua_isnone__JI = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("lua_luastate_x_lua_isnone", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG, ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle internal_native_x_lua_isnoneornil__JI = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("lua_luastate_x_lua_isnoneornil", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG, ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle internal_native_x_lua_isnumber__JI = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("lua_luastate_x_lua_isnumber", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG, ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle internal_native_x_lua_isstring__JI = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("lua_luastate_x_lua_isstring", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG, ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle internal_native_x_lua_istable__JI = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("lua_luastate_x_lua_istable", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG, ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle internal_native_x_lua_isthread__JI = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("lua_luastate_x_lua_isthread", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG, ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle internal_native_x_lua_isuserdata__JI = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("lua_luastate_x_lua_isuserdata", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG, ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle internal_native_x_lua_isyieldable__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("lua_luastate_x_lua_isyieldable", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_x_lua_len__JI = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("lua_luastate_x_lua_len", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle internal_native_x_lua_newtable__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("lua_luastate_x_lua_newtable", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_x_lua_newuserdatauv_addr__JII = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("lua_luastate_x_lua_newuserdatauv_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG, ValueLayout.JAVA_INT, ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle internal_native_x_lua_next__JI = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("lua_luastate_x_lua_next", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG, ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle internal_native_x_lua_call__JII = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("lua_luastate_x_lua_call", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_INT, ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle internal_native_x_lua_pcall__JIII = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("lua_luastate_x_lua_pcall", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG, ValueLayout.JAVA_INT, ValueLayout.JAVA_INT, ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle internal_native_x_lua_pop__JI = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("lua_luastate_x_lua_pop", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle internal_native_x_lua_pushboolean__JI = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("lua_luastate_x_lua_pushboolean", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle internal_native_x_lua_pushcclosure__JJI = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("lua_luastate_x_lua_pushcclosure", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG, ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle internal_native_x_lua_pushcfunction__JJ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("lua_luastate_x_lua_pushcfunction", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_x_lua_pushfstring_addr__JLjava_lang_String_2 = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("lua_luastate_x_lua_pushfstring_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG, ValueLayout.ADDRESS));

        static final java.lang.invoke.MethodHandle internal_native_x_lua_pushglobaltable__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("lua_luastate_x_lua_pushglobaltable", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_x_lua_pushinteger__JI = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("lua_luastate_x_lua_pushinteger", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle internal_native_x_lua_pushlightuserdata__JJ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("lua_luastate_x_lua_pushlightuserdata", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_x_lua_pushlstring_addr__JLjava_lang_String_2I = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("lua_luastate_x_lua_pushlstring_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG, ValueLayout.ADDRESS, ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle internal_native_x_lua_pushnil__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("lua_luastate_x_lua_pushnil", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_x_lua_pushnumber__JD = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("lua_luastate_x_lua_pushnumber", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_DOUBLE));

        static final java.lang.invoke.MethodHandle internal_native_x_lua_pushstring__JLjava_lang_String_2 = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("lua_luastate_x_lua_pushstring", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.ADDRESS));

        static final java.lang.invoke.MethodHandle internal_native_x_lua_pushthread__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("lua_luastate_x_lua_pushthread", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_x_lua_pushvalue__JI = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("lua_luastate_x_lua_pushvalue", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle internal_native_x_lua_rawequal__JII = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("lua_luastate_x_lua_rawequal", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG, ValueLayout.JAVA_INT, ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle internal_native_x_lua_rawget__JI = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("lua_luastate_x_lua_rawget", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG, ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle internal_native_x_lua_rawgeti__JII = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("lua_luastate_x_lua_rawgeti", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG, ValueLayout.JAVA_INT, ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle internal_native_x_lua_rawset__JI = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("lua_luastate_x_lua_rawset", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle internal_native_x_lua_rawseti__JII = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("lua_luastate_x_lua_rawseti", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_INT, ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle internal_native_x_lua_remove__JI = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("lua_luastate_x_lua_remove", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle internal_native_x_lua_replace__JI = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("lua_luastate_x_lua_replace", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle internal_native_x_lua_resetthread__JI = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("lua_luastate_x_lua_resetthread", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG, ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle internal_native_x_lua_rotate__JII = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("lua_luastate_x_lua_rotate", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_INT, ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle internal_native_x_lua_setfield__JILjava_lang_String_2 = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("lua_luastate_x_lua_setfield", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_INT, ValueLayout.ADDRESS));

        static final java.lang.invoke.MethodHandle internal_native_x_lua_setglobal__JLjava_lang_String_2 = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("lua_luastate_x_lua_setglobal", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.ADDRESS));

        static final java.lang.invoke.MethodHandle internal_native_x_lua_seti__JII = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("lua_luastate_x_lua_seti", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_INT, ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle internal_native_x_lua_setuservalue__JI = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("lua_luastate_x_lua_setuservalue", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG, ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle internal_native_x_lua_setiuservalue__JII = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("lua_luastate_x_lua_setiuservalue", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG, ValueLayout.JAVA_INT, ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle internal_native_x_lua_setmetatable__JI = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("lua_luastate_x_lua_setmetatable", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG, ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle internal_native_x_lua_settable__JI = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("lua_luastate_x_lua_settable", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle internal_native_x_lua_settop__JI = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("lua_luastate_x_lua_settop", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle internal_native_x_lua_status__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("lua_luastate_x_lua_status", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_x_lua_stringtonumber__JLjava_lang_String_2 = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("lua_luastate_x_lua_stringtonumber", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG, ValueLayout.ADDRESS));

        static final java.lang.invoke.MethodHandle internal_native_x_lua_toboolean__JI = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("lua_luastate_x_lua_toboolean", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG, ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle internal_native_x_lua_toclose__JI = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("lua_luastate_x_lua_toclose", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle internal_native_x_lua_tointeger__JI = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("lua_luastate_x_lua_tointeger", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG, ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle internal_native_x_lua_tonumber__JI = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("lua_luastate_x_lua_tonumber", FunctionDescriptor.of(ValueLayout.JAVA_DOUBLE, ValueLayout.JAVA_LONG, ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle internal_native_x_lua_topointer_addr__JI = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("lua_luastate_x_lua_topointer_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG, ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle internal_native_x_lua_tostring_addr__JI = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("lua_luastate_x_lua_tostring_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG, ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle internal_native_x_lua_touserdata_addr__JI = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("lua_luastate_x_lua_touserdata_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG, ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle internal_native_x_lua_type__JI = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("lua_luastate_x_lua_type", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG, ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle internal_native_x_lua_typename_addr__JI = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("lua_luastate_x_lua_typename_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG, ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle internal_native_x_lua_upvalueindex__JI = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("lua_luastate_x_lua_upvalueindex", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG, ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle internal_native_x_lua_version__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("lua_luastate_x_lua_version", FunctionDescriptor.of(ValueLayout.JAVA_DOUBLE, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_x_lua_warning__JLjava_lang_String_2I = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("lua_luastate_x_lua_warning", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.ADDRESS, ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle internal_native_x_lua_yield__JI = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("lua_luastate_x_lua_yield", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG, ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle internal_native_x_luaL_loadstring__JLjava_lang_String_2 = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("lua_luastate_x_lual_loadstring", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG, ValueLayout.ADDRESS));

        static final java.lang.invoke.MethodHandle internal_native_x_luaL_error__JLjava_lang_String_2 = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("lua_luastate_x_lual_error", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.ADDRESS));

        static final java.lang.invoke.MethodHandle internal_native_x_luaL_argerror__JILjava_lang_String_2 = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("lua_luastate_x_lual_argerror", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_INT, ValueLayout.ADDRESS));

        static final java.lang.invoke.MethodHandle internal_native_x_luaL_checkversion__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("lua_luastate_x_lual_checkversion", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_x_luaL_newmetatable__JLjava_lang_String_2 = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("lua_luastate_x_lual_newmetatable", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG, ValueLayout.ADDRESS));

        static final java.lang.invoke.MethodHandle internal_native_x_luaL_getmetafield__JILjava_lang_String_2 = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("lua_luastate_x_lual_getmetafield", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG, ValueLayout.JAVA_INT, ValueLayout.ADDRESS));

        static final java.lang.invoke.MethodHandle internal_native_x_luaL_getmetatable__JLjava_lang_String_2 = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("lua_luastate_x_lual_getmetatable", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG, ValueLayout.ADDRESS));

        static final java.lang.invoke.MethodHandle internal_native_x_luaL_getsubtable__JILjava_lang_String_2 = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("lua_luastate_x_lual_getsubtable", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG, ValueLayout.JAVA_INT, ValueLayout.ADDRESS));

        static final java.lang.invoke.MethodHandle internal_native_x_luaL_len__JI = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("lua_luastate_x_lual_len", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG, ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle internal_native_x_luaL_pushfail__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("lua_luastate_x_lual_pushfail", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_x_luaL_ref__JI = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("lua_luastate_x_lual_ref", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG, ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle internal_native_x_luaL_unref__JII = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("lua_luastate_x_lual_unref", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_INT, ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle internal_native_x_luaL_typeerror__JILjava_lang_String_2 = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("lua_luastate_x_lual_typeerror", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG, ValueLayout.JAVA_INT, ValueLayout.ADDRESS));

        static final java.lang.invoke.MethodHandle internal_native_createContext__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("lua_luastate_createcontext", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_destroyContext__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("lua_luastate_destroycontext", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_dumpStack_addr__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("lua_luastate_dumpstack_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_dumpTable_addr__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("lua_luastate_dumptable_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_setIntToVoid__JI = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("lua_luastate_setinttovoid", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle internal_native_getIntFromVoid__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("lua_luastate_getintfromvoid", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG));
    }
}
