/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package lua.natives;

import lua.*;

final public class JNI_LuaFunction {

    public static native void internal_native_deleteNative(long this_addr);

    public static native long internal_native_create_addr();
}
