/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package lua;

import com.github.xpenatan.jParser.api.NativeObject;
import com.github.xpenatan.jparser.runtime.helper.NativeString;

public class LuaState extends NativeObject {

    static public final LuaState NULL = LuaState.native_new();

    public LuaState() {
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected LuaState(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static LuaState native_new() {
        return new LuaState((byte) 0, (char) 0);
    }

    public void lua_absindex(int idx) {
    }

    public void lua_arith(int op) {
    }

    public int lua_checkstack(int n) {
        return 0;
    }

    public int lua_compare(int index1, int index2, int op) {
        return 0;
    }

    public void lua_concat(int op, int n) {
    }

    public void lua_copy(int fromidx, int toidx) {
    }

    public void lua_createtable(int narr, int nrec) {
    }

    public int lua_getfield(int index, String k) {
        return 0;
    }

    public int lua_getglobal(String name) {
        return 0;
    }

    public int lua_geti(int index, int i) {
        return 0;
    }

    public int lua_getmetatable(int index) {
        return 0;
    }

    public int lua_gettable(int index) {
        return 0;
    }

    public int lua_gettop() {
        return 0;
    }

    public int lua_getiuservalue(int index, int n) {
        return 0;
    }

    public void lua_insert(int index) {
    }

    public int lua_isboolean(int index) {
        return 0;
    }

    public int lua_iscfunction(int index) {
        return 0;
    }

    public int lua_isfunction(int index) {
        return 0;
    }

    public int lua_isinteger(int index) {
        return 0;
    }

    public int lua_islightuserdata(int index) {
        return 0;
    }

    public int lua_isnil(int index) {
        return 0;
    }

    public int lua_isnone(int index) {
        return 0;
    }

    public int lua_isnoneornil(int index) {
        return 0;
    }

    public int lua_isnumber(int index) {
        return 0;
    }

    public int lua_isstring(int index) {
        return 0;
    }

    public int lua_istable(int index) {
        return 0;
    }

    public int lua_isthread(int index) {
        return 0;
    }

    public int lua_isuserdata(int index) {
        return 0;
    }

    public int lua_isyieldable() {
        return 0;
    }

    public void lua_len(int index) {
    }

    public void lua_newtable() {
    }

    public NativeObject lua_newuserdatauv(int size, int nuvalue) {
        return null;
    }

    public int lua_next(int index) {
        return 0;
    }

    public void lua_call(int nargs, int nresults) {
    }

    public int lua_pcall(int nargs, int nresults, int msgh) {
        return 0;
    }

    public void lua_pop(int n) {
    }

    public void lua_pushboolean(int b) {
    }

    public void lua_pushcclosure(LuaFunction callback, int n) {
    }

    public void lua_pushcfunction(LuaFunction callback) {
    }

    public NativeString lua_pushfstring(String fmt) {
        return null;
    }

    public void lua_pushglobaltable() {
    }

    public void lua_pushinteger(int n) {
    }

    public void lua_pushlightuserdata(NativeObject n) {
    }

    public NativeString lua_pushlstring(String s, int len) {
        return null;
    }

    public void lua_pushnil() {
    }

    public void lua_pushnumber(double n) {
    }

    public void lua_pushstring(String s) {
    }

    public int lua_pushthread() {
        return 0;
    }

    public void lua_pushvalue(int index) {
    }

    public int lua_rawequal(int index1, int index2) {
        return 0;
    }

    public int lua_rawget(int index) {
        return 0;
    }

    public int lua_rawgeti(int index, int n) {
        return 0;
    }

    public void lua_rawset(int index) {
    }

    public void lua_rawseti(int index, int i) {
    }

    public void lua_remove(int index) {
    }

    public void lua_replace(int index) {
    }

    public int lua_resetthread(int index) {
        return 0;
    }

    public void lua_rotate(int index, int n) {
    }

    public void lua_setfield(int index, String k) {
    }

    public void lua_setglobal(String name) {
    }

    public void lua_seti(int index, int n) {
    }

    public int lua_setuservalue(int index) {
        return 0;
    }

    public int lua_setiuservalue(int index, int n) {
        return 0;
    }

    public int lua_setmetatable(int index) {
        return 0;
    }

    public void lua_settable(int index) {
    }

    public void lua_settop(int index) {
    }

    public int lua_status() {
        return 0;
    }

    public int lua_stringtonumber(String s) {
        return 0;
    }

    public int lua_toboolean(int index) {
        return 0;
    }

    public void lua_toclose(int index) {
    }

    public int lua_tointeger(int index) {
        return 0;
    }

    public double lua_tonumber(int index) {
        return 0;
    }

    public NativeObject lua_topointer(int index) {
        return null;
    }

    public NativeString lua_tostring(int index) {
        return null;
    }

    public NativeObject lua_touserdata(int index) {
        return null;
    }

    public int lua_type(int index) {
        return 0;
    }

    public NativeString lua_typename(int tp) {
        return null;
    }

    public int lua_upvalueindex(int i) {
        return 0;
    }

    public double lua_version() {
        return 0;
    }

    public void lua_warning(String msg, int tocont) {
    }

    public int lua_yield(int nresults) {
        return 0;
    }

    public int luaL_loadstring(String s) {
        return 0;
    }

    public void luaL_error(String fmt) {
    }

    public void luaL_argerror(int arg, String extramsg) {
    }

    public void luaL_checkversion() {
    }

    public int luaL_newmetatable(String tname) {
        return 0;
    }

    public int luaL_getmetafield(int obj, String fieldName) {
        return 0;
    }

    public int luaL_getmetatable(String tname) {
        return 0;
    }

    public int luaL_getsubtable(int idx, String fname) {
        return 0;
    }

    public int luaL_len(int index) {
        return 0;
    }

    public void luaL_pushfail() {
    }

    public int luaL_ref(int t) {
        return 0;
    }

    public void luaL_unref(int t, int ref) {
    }

    public int luaL_typeerror(int arg, String tname) {
        return 0;
    }

    public void createContext() {
    }

    public void destroyContext() {
    }

    public NativeString dumpStack() {
        return null;
    }

    public NativeString dumpTable() {
        return null;
    }

    public static void setIntToVoid(NativeObject pointer, int value) {
    }

    public static int getIntFromVoid(NativeObject pointer) {
        return 0;
    }
}
